### ISSUE TITLE
ffi not support？

### ISSUE THREAD

**Issue by SeaAndSand** [mah0x211/lua-pthread#1]
it‘s occoured error when i used ffi in the pthread.new()
got error: main.lua:12: attempt to index global 'ffi' (a nil value)

**Comment by mah0x211** [comment]
`pthread.new()` executes the passed script in a new Lua state. Therefore, it does not share any variables with the Lua state of the caller. So, you need to load the ffi module on the passed script.

```lua
--- this script has been tested with LuaJIT v2.0.5
local pthread = require('pthread')

local th = pthread.new([==[
local ffi = require('ffi')
ffi.cdef[[
int printf(const char *fmt, ...);
]]

ffi.C.printf("hello %s %s\n", ...)
]==], 'pthread', 'world!');
th:join()
```
